services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./App.py"
    depends_on:
      - db

  db:
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: 'alumnes'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - '3306:3306'